name: Ubuntu
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
      
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: lede-code01
        path: openwrt/bin/
